### ISSUE TITLE
csv-stringify does not work in Node 8.17.0 (TypeError: stringifier.off is not a function)

### ISSUE THREAD

**Issue by silverhero13** [adaltas/node-csv#294]
**Describe the bug**

The stringify function throws an error when I'm using Node 8.17.0 even though the documentation says that it runs in Node 7.6+.

**To Reproduce**

* Change your Node version to 8.17.0 (I used nvm)
* Open the Node REPL
* Copy and paste the following code:
```
csv = require('csv/lib/sync')
csv.stringify([], { header: true, delimiter: ',' })
```
* The package should return an error like this:
```
TypeError: stringifier.off is not a function
    at Object.module.exports [as stringify] ([redacted]/node_modules/csv-stringify/lib/sync.js:22:15)
```

**Comment by wdavidw** [comment]
Could you try using `var stringify = require('csv-stringify/lib/es5/sync')` instead and let us know, thank youl.

**Comment by silverhero13** [comment]
Unfortunately, it still doesn't work.

```
TypeError: stringifier.off is not a function
    at module.exports ([redacted]/node_modules/csv-stringify/lib/es5/sync.js:47:15)
```

**Comment by silverhero13** [comment]
Looks like it's really a Node version issue.

I noticed that `Stringifier` extends `stream.Transform`. So, I tried to take a look at the `off` method of `stream.Transform`. Here are the results:

* Node 8
```
> (new stream.Transform()).off
undefined
```
* Node 10
```
> (new stream.Transform()).off
[Function: removeListener]
```
* Node 14
```
> (new stream.Transform()).off
[Function (anonymous)]
```

**Comment by wdavidw** [comment]
Strange because we don't call `off` directly.

**Comment by wdavidw** [comment]
This is fixed in latest `6.0.4` version of `csv-stringify`.
